### ISSUE TITLE
Need help maintaining this?

### ISSUE THREAD

**Issue by SD10** [carolanitz/Awesome-iOS-Twitter#32]
@carolanitz I think this is a good project to connect developers in the iOS community. I noticed there is a growing backlog of open pull requests. If you need help maintaining the project and reviewing the PRs I'd be happy to assist you 😃

**Comment by carolanitz** [comment]
Yes please! I honestly just don't know where to draw the line and how to close a PR with "I don't want to merge this/ I'm not sure if that would be a good addition" without making people sad :D

**Comment by SD10** [comment]
I can understand that. I have a soft ❤️ too. The key is following your own code of conduct and just letting people know respectfully -- "I'm sorry but I don't think this fits the vision for the project."

Currently, CONTRIBUTING.md has a section that explains what makes a Twitter account ineligible. It may help both you and the contributors to create a section with the requirements for an ideal Twitter account.

This way:
a) You don't feel like you're judging people personally but instead, use a standard rubric.
b) You can give people a specific reason why their addition doesn't fit the project vision.

I think this sort of formalization should also decrease your workload for vetting all possible additions.

**Comment by carolanitz** [comment]
This is exactly the point where I don't know what to add as valid reason 🙃
 
I was thinking about adding 
- has at least 3000 followers on twitter for personal accounts (similar but less for conferences)
or
- made a major contribution to the community.

The first one is very easy to use but also a random chosen number. 
The second is simply very fuzzy. Any thoughts ?

**Comment by mikefinney** [comment]
I also empathize. 

For the fuzzy one..  "made a major contribution to the community. Examples include, has contributed to a popular open source project (like RxSwift)"

However, I understand that "popular open source" is fuzzy as well. At some point, it's a judgement call no matter what. True?

**Comment by SD10** [comment]
@carolanitz I think defining what makes a "valid" addition requires you to determine "what" you want this project to be -- or how big of a list you want it to be.

I think 3,000 followers is a pretty big number. I would be fine with 1,000 - 1,500 personally. I can't help but feel these are all arbitrary numbers.

Determining what is deemed a "major contribution" is definitely fuzzy and could be a touchy subject for some people.

**Activity**:
- Avg 20 iOS tweets per month (almost daily)

**Min Number of Tweets**:
- 750 tweets ( ~1 per day for 2 years )

**Followers**
- 1,500 for personal accounts
- 500 for conferences

**Exceptions**
- Creator of open source iOS project with 4,000+ stars

It really comes down to what _you_ want 😃 I can see why this is difficult, but hopefully discussing it will help refine the project vision.

**Comment by russjr08** [comment]
I'd be happy to help out too with reviews, I still actually have watch enabled for the repo, so they all come to my email anyways 😂

In terms of requirements, I think if you phrase them as "strongly recommended requirements" or something along those lines, it makes it a bit easier. Because like everything else, there's always going to be exceptions to the rules. If someone wants to suggest someone who doesn't meet the requirements, that's okay, but they'll need to present a strong case as to why they should be included.

**Comment by carolanitz** [comment]
Thank you for the comments and the feedback!  I added some eligibility criterias based on this thread https://github.com/carolanitz/Awesome-iOS-Twitter/commit/150b144479e9560a12ddaccb3ca60860c915e2a8

**Comment by SD10** [comment]
Great @carolanitz I'll close this issue 😃
